### ISSUE TITLE
Can't install with pip?

### ISSUE THREAD

**Issue by joshburkart** [Zulko/ddeint#1]
This seems like a great module! I love clean APIs like you seem to have implemented. Unfortunately pip seems to give me errors when trying to install; any ideas?

``` sh
josh@schism:~/Research/projects$ pip3 install ddeint
Collecting ddeint
  Using cached ddeint-0.1.02.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in /var/folders/sf/pl_p088d46304npx9csknxq40000gn/T/tmpesz7da9o
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/ez_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sf/pl_p088d46304npx9csknxq40000gn/T/pip-build-pqh28rf2/ddeint/setup.py", line 2, in <module>
        ez_setup.use_setuptools()
      File "/opt/anaconda3/lib/python3.5/site-packages/ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/opt/anaconda3/lib/python3.5/site-packages/ez_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/opt/anaconda3/lib/python3.5/site-packages/ez_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/opt/anaconda3/lib/python3.5/site-packages/ez_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
```

**Comment by surendra1472** [comment]
Hey did you fix this?

**Comment by sarahsama** [comment]
python3.5 does not work. Change your paython to 3.4

**Comment by fccoelho** [comment]
> python3.5 does not work. Change your paython to 3.4

Rolling back the Python version is not a sensible solution. It doesn't seem too hard to simply fix the bug in setup.py. Using ez-setup.py is no longer the recommended way to writing a setup script which rely on setuptools.
https://setuptools.readthedocs.io/en/latest/ez_setup.html?highlight=ez_setup

**Comment by Zulko** [comment]
``pip3 install ddeint`` seems to work for me (python 3.6). Maybe this is something specific to python 3.5 (at which case it's not worth a fix). Are we sure this is even linked to ez_setup, and not to a system rights problem ?

**Comment by fccoelho** [comment]
it failed for me  on python 3.6:

```python
sudo -H pip3 install -U ddeint
[sudo] senha para fccoelho: 
Collecting ddeint
  Downloading https://files.pythonhosted.org/packages/f8/e0/551123d86a28c17531d2700c5e41a6b5b46ca995ca391fb83a60bdf056d4/ddeint-0.1.02.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-et2clkqr/ddeint/setup.py", line 1, in <module>
        import ez_setup
    ModuleNotFoundError: No module named 'ez_setup'
```
And it does seem to be an issue with ez_setup.py

I would just delete the first two lines of 
https://github.com/Zulko/ddeint/blob/master/setup.py

and make sure you have `setuptools` installed on your system before installing the package. 
By the way I believe that if you have `pip` installed you must have `setuptools` as well.

**Comment by Zulko** [comment]
Ok that actually sounds like a MANIFEST.in issue (the ez_setup.py file was missing from the manifest so not shipped with the library).

I hear you regarding the deprecation of ez_setup, but it should still work with it.

**Comment by sarahsama** [comment]
It is possible to install by pip too. pip3 install Charm-Crypto

________________________________

**Comment by Zulko** [comment]
Fixed in the new version (reopen if not)
