### ISSUE TITLE
May I contribute your package to conda-forge?

### ISSUE THREAD

**Issue by JunSeokCha** [Zulko/ddeint#12]
Dear Zulko,

Hello Zulko, my name is JunSeokCha. May I contribute your package to conda-forge?

Sincerely,
JunSeokCha

**Comment by Zulko** [comment]
Hi JunSeokCha, yes please go for it. If there ever was an update to this package, would it be automatically updated on conda?

**Comment by JunSeokCha** [comment]
Thank you Zulko for your answer. I would have to manually update it periodically.

**Comment by JunSeokCha** [comment]
I would like to discuss two things with you:

- You need to add a license file to your package, not just on the readme. This is required to make the conda-forge recipe.
I believe that BSD-3-Clause license matches the description on your package's readme.

- You need to decide who will be the maintainer of the conda-forge feedstock.
The maintainer’s job is to:

Keep the feedstock updated by merging eventual maintenance PRs from conda-forge’s bots.

Keep the feedstock on par with new releases of the source package by:

Bumping the version number and checksum.

Making sure that the feedstock’s requirements stay accurate.

Make sure the test requirements match those of the updated package.

Answer eventual questions about the package on the feedstock issue tracker.

If you would like to be the maintainer of the conda-forge feedstock, then I will submit your name as the maintainer of feedstock in the conda-forge recipe. If you would not like to be the maintainer of the conda-forge feedstock, then I will submit my name on the conda-forge recipe as maintainer of feedstock.

**Comment by Zulko** [comment]
- I'll add a MIT license to the package for simplicity (that's what I use for my other Python projects).
- Would you be ok being the conda maintainer if that's not too much trouble?

**Comment by Zulko** [comment]
Actually I noticed that the readme said "public domain" so I added a public domain LICENSE file (CC0)

**Comment by JunSeokCha** [comment]
Zulko, thank you for your answer. I will be the conda maintainer. Thank you for adding the license file.

**Comment by JunSeokCha** [comment]
I am happy to tell you that ddeint succeeded to be contributed to conda-forge. (https://github.com/conda-forge/ddeint-feedstock)
