### ISSUE TITLE
Citing ddeint

### ISSUE THREAD

**Issue by yoavram** [Zulko/ddeint#7]
If you use Zenodo or some other repository to deposit ddeint and create a DOI, we could cite it when we use it in our work.

**Comment by Zulko** [comment]
I'll look into it later, but for now this package could also be cited as you would cite a software or website without any publication, something like [in this paper](https://www.medrxiv.org/content/10.1101/2020.05.23.20111500v1.full.pdf+html):

*Zulko (2019). Scipy-based delay differential equation (dde) solver. https://pypi.org/project/ddeint.*

**Comment by yoavram** [comment]
Great, thanks, I'll cite it that way. You package was very helpful.
