### ISSUE TITLE
Self adjusting integration step?

### ISSUE THREAD

**Issue by Firigion** [Zulko/ddeint#8]
Not an issue per se, but the only way I can think of contacting you. This package uses scipy's `odeint` in the background, right? `odeint` has a self adjusting time step, such that the array of time instants used is only an array to query the integrated function in, not the actual time steps. Does `ddeint` not do the same? From what I gather from the code, it should, but when integrateing a simple one variable regulatory function I get different results depending on the time array passed to the function, for some parameters. So much so, that in some cases it diverges awfuly due to numerical errors, and in other cases it correctly displays oscilations.

This is the function in question, just in case:
```python
def model(x, t, d, b, x0, h, tau):
    return -d * x(t) + b/(1+(x(t-tau)/x0)**h)
```

**Comment by Zulko** [comment]
Yeah sorry for that, there is no step self-adjustment unfortunately, the only way to check for validity is to check for convergence (basically "do I get the same final values with a smaller step size?").

**Comment by Firigion** [comment]
Oh, that's alright. I was just wondering why I got those results, but if it's WAI, I'll just close the issue. Thanks!
